### ISSUE TITLE
the following line fails in AWS

### ISSUE THREAD

**Issue by javascriptCoder78** [Mashape/kong-dist-cloudformation#17]
wget -O kong.rpm downloadkong.org/aws.rpm\n

the rpm downloaded is corrupt one and cloud formation fails

this is for the following template

kong-elb-postgres-optional-vpc-new-hvm.template

**Comment by shashiranjan84** [comment]
@javascriptCoder78 Thanks for informing us. Templates have been updated to resolve the issue.
