### ISSUE TITLE
DBHost should have a Default of ""

### ISSUE THREAD

**Issue by lox** [Mashape/kong-dist-cloudformation#24]
Need to provide a default of "" for DBHost, otherwise you get the following error when creating a stack:

`An error occurred (ValidationError) when calling the CreateStack operation: Parameters: [DBHost] must have values`

https://github.com/Mashape/kong-dist-cloudformation/blob/master/templates/kong-elb-postgres-optional-vpc-new-hvm.template#L13

**Comment by shashiranjan84** [comment]
Thanks @lox, that template will soon be removed, Please use, 
https://raw.githubusercontent.com/Mashape/kong-dist-cloudformation/master/templates/kong-elb-postgres-optional-vpc-optional-hvm.template

or 

any of the templates from 

https://getkong.org/install/aws-cloudformation/

**Comment by lox** [comment]
Cheers, I ended up rewriting it in YAML anyway :)
