### ISSUE TITLE
AutoScaling group fails to create

### ISSUE THREAD

**Issue by pacey** [Mashape/kong-dist-cloudformation#39]
Hey! This probably isn't an issue with the CFN template you have written but I wondering if you have ever seen the following error?

```

14:41:38 UTC+0000 | ROLLBACK_IN_PROGRESS | AWS::CloudFormation::Stack | kong-elb-postgres-hvm-staging | The following resource(s) failed to create: [KongScalingGroup]. . Rollback requested by user.
14:41:37 UTC+0000 | CREATE_FAILED | AWS::AutoScaling::AutoScalingGroup | KongScalingGroup | Received 1 FAILURE signal(s) out of 1. Unable to satisfy 100% MinSuccessfulInstancesPercent requirement
```

I can't catch any of the logs as the stack deletes itself when the resource fails to create. Any ideas?

**Comment by shashiranjan84** [comment]
What I can say that, Kong instance fails to signal that it successfully started https://github.com/Kong/kong-dist-cloudformation/blob/master/templates/kong-elb-postgres-optional-vpc-optional-hvm.template#L627. Good way of debugging this would be disabling rollback and check cloud-init log in the Kong instance.
