### ISSUE TITLE
When running cloud-formation template for Postgres, Migration fails.

### ISSUE THREAD

**Issue by FrankKerschbaumer3** [Mashape/kong-dist-cloudformation#47]
Hi,

I am using the us-east1 Postgres cloudformation template and and getting following error while attempting to install.

`Received 1 FAILURE signal(s) out of 1. Unable to satisfy 100% MinSuccessfulInstancesPercent requirement`

Looking at the cloud init log in the ec2 instance I am getting...

```
Error: /usr/local/share/lua/5.1/kong/cmd/start.lua:51: nginx: [error] init_by_lua error: /usr/local/share/lua/5.1/kong/init.lua:158: database needs bootstrap; run 'kong migrations bootstrap'
stack traceback:
	[C]: in function 'error'
	/usr/local/share/lua/5.1/kong/init.lua:158: in function 'init'
	init_by_lua:3: in main chunk


  Run with --v (verbose) or --vv (debug) for more details
database needs bootstrapping; run 'kong migrations bootstrap'
Error: Kong is not running at /usr/local/kong

  Run with --v (verbose) or --vv (debug) for more details
nginx.......not running

[kong] failed to start kong, exiting...
Cloud-init v. 0.7.6 finished at Wed, 19 Sep 2018 17:57:09 +0000. Datasource DataSourceEc2.  Up 89.33 seconds
```
I have used multiple versions of Postgres as well as verifying if the ec2 instance can reach the DB that it is creating.

Steps to recreate: Run the template.

Thanks and have a great day!

**Comment by abrokenjester** [comment]
We are seeing the same problem when using this template.

**Comment by alhazmy13** [comment]
same issue

**Comment by FrankKerschbaumer3** [comment]
I solved this issue by using the command '

**Comment by berry2012** [comment]
Same issue
Received 1 FAILURE signal(s) out of 2. Unable to satisfy 100% MinSuccessfulInstancesPercent requirement
--
  | 20:09:55 UTC+0100 | CREATE_IN_PROGRESS | AWS::AutoScaling::AutoScalingGroup | KongScalingGroup | Received FAILURE signal with UniqueId i-0ead158ff6ccc81ec

**Comment by hbagdi** [comment]
ping @shashiranjan84

**Comment by shashiranjan84** [comment]
@alhazmy13 @berry2012  thanks for reporting the issue. It has been fixed now. I am closing the ticket for now, if issue still persists please reopen the ticket.
