### ISSUE TITLE
Kong with PostgreSQL for aws cloudformation template (HVM for ap-southeast-2) condition statement issue

### ISSUE THREAD

**Issue by mattsjk** [Mashape/kong-dist-cloudformation#53]
I was looking at using the Kong with PostgreSQL for aws cloudformation template (HVM for ap-southeast-2) and noticed that the condition statement for "UseAZParameter" does not make sense
```
"UseAZParameter": { "Fn::Not" : [ {"Fn::And" : [ { "Fn::Equals" : [ { "Ref" : "Subnet1AZ" }, "" ]} , { "Fn::Equals" : [ { "Ref" : "Subnet1AZ" }, "" ] } ] } ] }
```
Was wondering if the equals statement should both be Subnet1AZ which does not make much sense? I think it should have been Subnet2AZ for the second part of the equals statement

**Comment by shashiranjan84** [comment]
@mattsjk you are right it does not. I have updated the condition. Thanks for bringing it to our notice.
